dbfilename redis_queue.rdb
dir /home/twenty/frappe/cardboard-bench/config/pids
pidfile /home/twenty/frappe/cardboard-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/twenty/frappe/cardboard-bench/config/redis_queue.acl
